#mybatis.config-location=classpath:mybatis-config.xml
#mybatis mapper文件的位置
#扫描pojo类的位置,在此处指明扫描实体类的包，在mapper中就可以不用写pojo类的全路径名了
mybatis:
  type-aliases-package: com.spider.bean
  mapper-locations: classpath:mapper/*.xml
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/spiderhouse?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: 你的数据库用户名，一般为root
    password: 与用户名匹配的密码
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    password:
    host: 127.0.0.1
    port: 6379
lbs:
  webApi: http://restapi.amap.com/v3/assistant/coordinate/convert
  webKey: 
server:
  port: 8097 
    #如果运行中报端口占用错误，修改这个端口号
